### ISSUE TITLE
Remove existing dependency on maptools and sp

### ISSUE THREAD

**Issue by freysimon** [hzambran/hydroTSM#21]
The packages sp and maptools are close to their end of life and will be not available from October 2023 on cran (see https://r-spatial.org/r/2022/04/12/evolution.html). Is there any chance to remove the dependencies of those packages?

**Comment by MichaelChirico** [comment]
FWIW sp is not getting EOL'd, only maptools.

**Comment by freysimon** [comment]
True. Thanks for the info.

**Comment by MichaelChirico** [comment]
I don't have enough context on hydroTSM to offer a more complete migration than #22. The best approach in my opinion is to switch to `sf` entirely, which means `maptools::readShapePoly()` :arrow_right: `sf::st_read()`. But that may have cascading effects, since the returned object is a different class.

This suggests we might use `as(., "Spatial")` to try and convert back to an `sp`-friendly class, which hopefully retains more back-compatibility... but in a simple test case this didn't work _exactly_ (I haven't investigated further):

```r
library(maptools)
library(sp)
library(sf)

old = readShapePoly(system.file("shape", "nc.shp", package="sf"))
new = st_read(system.file("shape", "nc.shp", package="sf"))

isTRUE(all.equal(old, as(new, "Spatial")))
# [1] FALSE
```

So if we want an exact concordance more effort will be needed.

OTOH, I see both of the functions using `maptools::readShapePoly()` are marked as deprecated:

https://github.com/hzambran/hydroTSM/blob/b3f749f5f998f7a1fcd504f2c1b35c2aac0d6139/R/hydrokrige.R#L161
https://github.com/hzambran/hydroTSM/blob/b3f749f5f998f7a1fcd504f2c1b35c2aac0d6139/R/hydrokrige.R#L1114
https://github.com/hzambran/hydroTSM/blob/b3f749f5f998f7a1fcd504f2c1b35c2aac0d6139/R/mspplot.R#L79

So maybe the really simplest thing to do is complete the deprecation process & delete those functions.
